[request_definition]
r = sub, task, obj, act, kind

[policy_definition]
p = sub, task, obj, act, kind

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.task == p.task && r.obj == p.obj && r.act == p.act && r.kind == p.kind
